export const sample_foods = [
  {
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 200,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    name: 'Meatball',
    price: 350,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    name: 'Hamburger',
    price: 300,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    name: 'Fried Potatoes',
    price: 250,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    name: 'Chicken Soup',
    price: 350,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    name: 'Vegetables Pizza',
    price: 250,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];

export const sample_users = [
  {
    name: 'Prakash Mane',
    email: 'Prakashprm710@gmail.com',
    password: '12345',
    address: 'Mumbai',
    isAdmin: true,
  },
  {
    name: 'Srishti Chauhan',
    email: 'srishtichauhanchauhan1@gmail.com',
    password: '12345',
    address: 'Delhi',
    isAdmin: true,
  },
];
